### ISSUE TITLE
InitError on Windows loading libcleri.dll

### ISSUE THREAD

**Issue by jamesgardner1421** [libAtoms/ExtXYZ.jl#6] opened 2021-08-17 13:16 UTC
I noticed this issue when attempting to use the latest version of JuLIP which no longer works on windows due to this package. The error I encounter is:
```
julia> using ExtXYZ
[ Info: Precompiling ExtXYZ [352459e4-ddd7-4360-8937-99dcb397b478]
ERROR: LoadError: LoadError: InitError: could not load library "C:\Users\james\.julia\artifacts\465749424f91519e30d0c324b5228a91738a5131\bin\libcleri.dll"
Access is denied.
```
From what I understand dlopen cannot open the library since it has not been marked as executable. I checked the permissions for libcleri.dll in the [windows tarball](https://github.com/JuliaBinaryWrappers/libcleri_jll.jl/releases/tag/libcleri-v0.12.1%2B1) and it's `-rw-r--r--` whereas for `libextxyz.dll` it's `-rwxr-xr-x`.

There's been some discussion about this [previously](https://github.com/JuliaLang/julia/issues/38993) where they manually changed the permissions during the build with chmod but there was [an update which is supposed to do this automatically](https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/992). So here it should've been fixed automatically like with `libextxyz.dll` but for some reason it's not working?

I noticed that the CI only runs on mac and linux so maybe windows support isn't intended? But if this could be fixed that would be great.

**Comment by jameskermode** [comment] 2021-08-17 13:18
Thanks for reporting, will try to take a look ASAP. I don't have a windows machine to test on, but can certainly enable Windows on the CI.

**Comment by jameskermode** [comment] 2021-08-17 13:44
Reproduced in CI: https://github.com/libAtoms/ExtXYZ.jl/runs/3351081827?check_suite_focus=true#step:6:58

**Comment by jameskermode** [comment] 2021-08-17 16:06
Attempted fix to build recipe for libcleri is at https://github.com/JuliaPackaging/Yggdrasil/pull/3507. I will update here once that's been merged and propagated through to ExtXYZ.jl. I think I shouldn't have to make a new release since it will automatically use the latest build of the `libcleri_jll` package, but let's see.

**Comment by jameskermode** [comment] 2021-08-17 17:26
Ok, that permissions problem is now fixed but I see the tests are failing on Windows due to differences in libc. I should be able to fix that later, then will match a patch release of this package.

**Comment by jameskermode** [comment] 2021-08-17 18:12
CI now passing on Windows. If you confirm if fixes your problem I'll tag a new patch release.

Thanks again for reporting and very helpful investigations into what was going wrong.

**Comment by jamesgardner1421** [comment] 2021-08-17 18:15
Yep it's working for me now too. Thanks a lot!

**Comment by jameskermode** [comment] 2021-08-17 18:25
Great - I've tagged `v0.1.1` which should appear in the General registry shortly, so I'll close this issue. I think JuLIP should pick this up automatically since I didn't specify a particular version, but if not please re-open this.

**Closed by jameskermode** 2021-08-17 18:25 UTC
